- config/locales/typus.ja.yml
> translate items in typus.ja from en to ja

- app/assets/javascripts/checkin.coffee
- app/assets/javascripts/shop.coffee
- app/assets/stylesheets/checkin.scss
- app/assets/stylesheets/shop.scss
- app/controllers/checkin_controller.rb
- app/controllers/shop_controller.rb
- app/helpers/checkin_helper.rb
- app/helpers/shop_helper.rb
- app/views/checkin/index.html.erb
- config/routes.rb
- test/controllers/checkin_controller_test.rb
- test/controllers/shop_controller_test.rb
お店の一覧情報を表示するページを作成
controllerでお店の一覧情報を持ってくる
それらをview画面で一覧表示
チェックインボタンを作る
> チェックインページを作る

- app/controllers/application_controller.rb
- app/controllers/drinker/omniauth_callbacks_controller.rb
- app/controllers/drinkers/omniauth_callbacks_controller.rb
- app/models/drinker.rb
- config/environments/development.rb
- config/initializers/devise.rb
- config/routes.rb
/drinker/auth/facebookにアクセスすることで、facebookログイン機能が実行され、コールバックから自動的にユーザーdrinkerに追加するところまでできました。
> Feature facebook login

- app/controllers/drinker/omniauth_callbacks_controller.rb
登録、またはログインした段階でサインインされるように修正しました。
> Modify amniauth_callbacks_controller.rb

- app/controllers/application_controller.rb
- app/controllers/checkins_controller.rb
- app/models/drinker.rb
- config/routes.rb
#やったこと
チェックイン状況によってリンク先URLが変わる仕組みを作りました。
#仕組み
checkins#show
で、ユーザーがチェックイン済み時かどうか確認を行います。
ここで未チェックインであった場合、
/checkins/new
で、チェックインする店を選び、送信を押すとcheckins#createでデータベースへの保存を行い、
restaurants/:id
へリダイレクトする処理を行います。
また、チェックイン済みであった場合、/checkins/newをスキップして
restaurants/:id
へリダイレクトする処理を行います。
> チェックイン状況によるリンク先URLの変更

- app/controllers/checkins_controller.rb
checkins/new画面の送信を押すことでcheckinテーブルへデータを保存できるようにしました。
> checkinテーブルへのデータ保存

- app/controllers/drinkers_controller.rb
- app/views/drinkers/show.html.erb
> プロフィール画面の飲酒ログの表示

- app/controllers/checkins_controller.rb
- app/controllers/drinker/omniauth_callbacks_controller.rb
- config/routes.rb
- チェックインの状態に応じて遷移先を切り替える
- checkinsのshowアクションはなくても良いと思ったので、ルートを削除して処理を移動した
> サインアップ・サインイン後の遷移先を変更

- app/controllers/drinker/omniauth_callbacks_controller.rb
- app/controllers/drinkers_controller.rb
- app/models/drinker.rb
- app/models/ticket.rb
- config/routes.rb
/signup?passcode=xxxxxx
にリクエストを送ると、facebookログインに誘導して、同意した場合にはpasscodeとuserを紐付けて登録するところまで、完成しました。
> Feature relation ticket with drinker

- app/views/restaurants/map.html.erb
> add twitter window

- app/controllers/drinkers_controller.rb
- app/views/drinkers/login.html.erb
- config/routes.rb
> add login view

- app/assets/stylesheets/restaurants.scss
- app/views/restaurants/_show.html.erb
- app/views/restaurants/map.html.erb
自動的に混雑状況の色と画像が切り替わるようになりました。
画像は未定義なので、アイコンとしました。
> Feature below the map

- app/assets/stylesheets/festivals.scss
- app/assets/stylesheets/shared/_footer.scss
- app/assets/stylesheets/shared/_header.scss
- app/views/festivals/thewinner.html.erb
・ヘッダーとフッター高さをデザイン側に合わせました。
・文字の 位置とサイズと色 をデザイン側に合わせました。
・背景画像はこのコミットに含んでおりませんが、背景画像などはCSSのbackground-imageに差し込めば下記のようになります。
> Feature thewinner style

- app/assets/stylesheets/drinkers.scss
- app/views/drinkers/edit.html.erb
変更
「ユーザーネーム」　→　「トランキーロネーム（酒吞みニックネーム）」
「飲み歩き伝」　→　「呑みログ」
追加
「日付に時間（hh:mm）」
「※トランキーロネーム、称号、呑みログは公開されます」
> Hotfix modify profile

- app/controllers/drinkings_controller.rb
- app/controllers/restaurants_controller.rb
- app/models/drinking.rb
- app/models/sake.rb
- app/models/sake_temperature.rb
- app/models/vote.rb
- app/views/drinkings/_cancel_modal.html.erb
- app/views/drinkings/_modal.html.erb
- app/views/drinkings/_save.js.erb
- app/views/drinkings/_show.html.erb
- app/views/drinkings/create.html.erb
- app/views/drinkings/create.js.erb
- app/views/drinkings/destroy.js.erb
- app/views/drinkings/show.js.erb
- app/views/restaurants/_show.html.erb
- app/views/restaurants/show.html.erb
- config/routes.rb
あとデフォルト値を設定するとか、一人一票のバリデーションとか。
> 投票を取り消す機能の実装

- app/views/drinkers/edit.html.erb
- config/routes.rb
> Hotfix profile path

- app/controllers/drinker/omniauth_callbacks_controller.rb
- app/controllers/drinkers_controller.rb
- app/models/drinker.rb
- app/models/ticket.rb
サインアップの際にパスコードを入力しなくてもログインできてしまうバグを修正しました。
> Hotfix passcode

- app/assets/stylesheets/drinkers.scss
- app/controllers/drinker/omniauth_callbacks_controller.rb
- app/controllers/drinkers_controller.rb
- app/models/drinker.rb
- app/models/ticket.rb
- app/views/drinkers/login.html.erb
・ご指摘を受けたDrinkerModelの find_byを二度呼び出すところを１つにしました。
・存在しないパスコードを入力された時にエラーを返すようにしました。(Drinker.find_for_facebook_oauth)
・既に使われているパスコードを入力された時にエラーを返すようにしました。(Drinker.find_for_facebook_oauth)
・エラーメッセージが表示される前にreset_sessionされてしまうので、DrinkersController resetアクションで、受け取った値を再度設定する処理を書きました。
・ログイン画面にエラーメッセージを表示するようにしました。
・ログイン画面のエラーメッセージに色をつけました。
・セミコロンを削除しました
・unusedメソッドを修正しました
・エラーメッセージがない時にpタグを表示しないように変更しました。
> Feature login error message

- app/models/drinker.rb
- app/views/drinkers/edit.html.erb
・プロフィールのログ画面の日時フォーマットを修正しました。
%Y.%m.%d %h:%s  ->  %Y.%m.%d %H:%s
・変数名を正しく修正しました。
> プロフィール画面の時間表示を変更

- app/assets/stylesheets/festivals.scss
- app/views/festivals/thewinner.html.erb
> 投票結果画面の画像適用

- app/views/drinkers/edit.html.erb
> フォーマットを修正しました。(2)

- app/assets/stylesheets/restaurants.scss
お酒の画像を入れてなくてすみません。面倒くさいです。
before | after
---- | ----
> 投票画面のスタイルを調整

- app/assets/stylesheets/shared/_header.scss
> ヘッダが常に前に出るように修正

- app/assets/stylesheets/drinkers.scss
> ネーム入力欄が画面からはみ出ないように幅を指定

- app/assets/javascripts/restaurants.js
- app/views/restaurants/_show.html.erb
JSON部分(_show.html.erb)
スコアを表示する部分です。(restaurants.js)
> 評価したお酒の評価値を表示しました。

- app/views/drinkings/_modal.html.erb
星を選択せずに評価すると見た目が★3ですが、実際には★1で評価されてしまう部分を修正しました。
（selectの初期値を設定しました。）
> 評価の初期値を設定しました。

- app/views/restaurants/map.html.erb
消したUI
・拡大ボタン
・ストリートビュー
・マップの切り替えボタン
> GoogleMapのUIを消しました
